---
title: "for my dear little sister NanLin"
author: "Ran Huang"
date: "12/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries
```{r}
library(forecast)
library(vars)
library(MASS)
library(strucchange)
library(zoo)
library(psych)
library(ModelMetrics)
```

# load data
# split to training set and validation set
```{r}
train <- read.csv("Data/train.csv",header=T)
test <- read.csv("Data/test.csv",header=T)

br_rate <- ts(train$Bankruptcy_Rate, start = c(1987, 1), frequency = 12)
unemp <- ts(train$Unemployment_Rate, start = c(1987, 1), frequency = 12)
population <- ts(train$Population, start = c(1987, 1), frequency = 12)
house_price <- ts(train$House_Price_Index, start = c(1987, 1), frequency = 12)

unemp_ft <- ts(test$Unemployment_Rate, start = c(2015, 1), frequency = 12)
population_ft <- ts(test$Population, start = c(2015, 1), frequency = 12)
house_price_ft <- ts(test$House_Price_Index, start = c(2015, 1), frequency = 12)

train_br_rate <- ts(train$Bankruptcy_Rate, start = c(1987, 1), end =c(2008, 12),frequency = 12)
train_unemp <- ts(train$Unemployment_Rate, start = c(1987, 1), end =c(2008, 12),frequency = 12)
train_population <- ts(train$Population, start = c(1987, 1), end =c(2008, 12),frequency = 12)
train_house_price <- ts(train$House_Price_Index, start = c(1987, 1), end =c(2008, 12),frequency = 12)

vali_br_rate <- ts(train$Bankruptcy_Rate[265:336], start = c(2009, 1), end =c(2014, 12),frequency = 12)
vali_unemp <- ts(train$Unemployment_Rate, start = c(2009, 1), end =c(2014, 12),frequency = 12)
vali_population <- ts(train$Population, start = c(2009, 1), end =c(2014, 12),frequency = 12)
vali_house_price <- ts(train$House_Price_Index, start = c(2009, 1), end =c(2014, 12),frequency = 12)
```


# SARIMAX [(3,1,4)*(3,0,2),xreg = log.uer]
```{r}
bestModel <- arima(log(br_rate), order = c(3,1,4), seasonal = list(order = c(3,0,2), period = 12), xreg = data.frame(log(unemp)), method = "CSS")




```

```{r}
lowerB <- ts(exp(pred_logbr$lower), start = c(2015,1), frequency = 12)
upperB <- ts(exp(pred_logbr$upper), start = c(2015,1), frequency = 12)
predB <- ts(exp(pred_logbr$mean), start = c(2015,1), frequency = 12)
fit <- br_rate-bestModel$residuals

pred.result <- data.frame(time(lowerB),lowerB,predB,upperB)
names(pred.result) <- c('Time',"Lower Bound(95%)", "Mean Prediction", "Upper Bound(95%)")
pred.result

time(lowerB)


plot(br_rate,xlim=c(1987, 2018),ylim=c(0,6),main='forecast bankrupt rate for 2015-2017',xlab='year', ylab='')
tmp <- seq(from = 2015, by = 1/12, length = 36)
polygon(x= c(tmp,rev(tmp)),y= c(upperB,rev(lowerB)), col="lightgrey", border=NA)
points(predB,type='l',col='red')
points(lowerB,type='l',col='grey')
points(upperB,type = 'l',col='grey')
points(fit,type='l',lwd=0.6,col='blue')
legend(1987, 5, legend=c("1987 Jan - 2014 Dec [Actual]","2009 Jan - 2014 Dec [fitted]", "2015 Jan - 2017 Dec [Predicted]"),col=c("black", "blue","red"), lty=1:2, cex=0.7)
```

